//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Estro.TinyGest.Entities
{
    public partial class InvoiceEntities : ObjectContext
    {
        public const string ConnectionString = "name=InvoiceEntities";
        public const string ContainerName = "InvoiceEntities";
    
        #region Constructors
    
        public InvoiceEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public InvoiceEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public InvoiceEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Customer> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;
    
        public ObjectSet<Invoice> Invoices
        {
            get { return _invoices  ?? (_invoices = CreateObjectSet<Invoice>("Invoices")); }
        }
        private ObjectSet<Invoice> _invoices;
    
        public ObjectSet<InvoiceLine> InvoiceLines
        {
            get { return _invoiceLines  ?? (_invoiceLines = CreateObjectSet<InvoiceLine>("InvoiceLines")); }
        }
        private ObjectSet<InvoiceLine> _invoiceLines;
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;
    
        public ObjectSet<Order> Orders
        {
            get { return _orders  ?? (_orders = CreateObjectSet<Order>("Orders")); }
        }
        private ObjectSet<Order> _orders;
    
        public ObjectSet<OrderLine> OrderLines
        {
            get { return _orderLines  ?? (_orderLines = CreateObjectSet<OrderLine>("OrderLines")); }
        }
        private ObjectSet<OrderLine> _orderLines;
    
        public ObjectSet<OrderNote> OrderNotes
        {
            get { return _orderNotes  ?? (_orderNotes = CreateObjectSet<OrderNote>("OrderNotes")); }
        }
        private ObjectSet<OrderNote> _orderNotes;
    
        public ObjectSet<InvoiceNote> InvoiceNotes
        {
            get { return _invoiceNotes  ?? (_invoiceNotes = CreateObjectSet<InvoiceNote>("InvoiceNotes")); }
        }
        private ObjectSet<InvoiceNote> _invoiceNotes;

        #endregion
    }
}
